// Mocks generated by Mockito 5.4.2 from annotations
// in btc_demo/test/lib/wallet_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:btc_demo/lib/backend_api.dart' as _i3;
import 'package:btc_demo/lib/coins_price_repository.dart' as _i5;
import 'package:coingecko_api/coingecko_api.dart' as _i2;
import 'package:coingecko_api/data/market_chart_data.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCoinGeckoApi_0 extends _i1.SmartFake implements _i2.CoinGeckoApi {
  _FakeCoinGeckoApi_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BackendApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackendApi extends _i1.Mock implements _i3.BackendApi {
  MockBackendApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<double> getBtcBalance() => (super.noSuchMethod(
        Invocation.method(
          #getBtcBalance,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);
}

/// A class which mocks [CoinsPriceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoinsPriceRepository extends _i1.Mock
    implements _i5.CoinsPriceRepository {
  MockCoinsPriceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CoinGeckoApi get coinGeckoApi => (super.noSuchMethod(
        Invocation.getter(#coinGeckoApi),
        returnValue: _FakeCoinGeckoApi_0(
          this,
          Invocation.getter(#coinGeckoApi),
        ),
      ) as _i2.CoinGeckoApi);
  @override
  _i4.Future<double> getBtcToUsdPrice() => (super.noSuchMethod(
        Invocation.method(
          #getBtcToUsdPrice,
          [],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);
  @override
  _i4.Future<List<_i6.MarketChartData>> getCoinToUsdPriceHistory({
    required String? coinId,
    required int? days,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCoinToUsdPriceHistory,
          [],
          {
            #coinId: coinId,
            #days: days,
          },
        ),
        returnValue: _i4.Future<List<_i6.MarketChartData>>.value(
            <_i6.MarketChartData>[]),
      ) as _i4.Future<List<_i6.MarketChartData>>);
}
